export const fontConfig = {
  sansName: "Noto Sans Thai",
  monoName: "Geist Mono",
} as const;

export const appCopy = {
  language: "th",
  productName: "Quick Poll",
  metadata: {
    title: "Quick Poll | สร้างโพลสดทันที",
    createTitle: "สร้างโพล | Quick Poll",
    hostTitle: (roomCode: string) => `ผู้สร้างห้อง ${roomCode} | Quick Poll`,
    voterTitle: (roomCode: string) => `โหวตห้อง ${roomCode} | Quick Poll`,
    description: "สร้างโพลสดและให้โหวตแบบเรียลไทม์โดยไม่ต้องล็อกอิน",
  },
  home: {
    subtitle: "โหวตสดทันที",
    titleLabel: "ชื่อโพล",
    questionLabel: "คำถาม",
    choicesLabel: "ตัวเลือก",
    titlePlaceholder: "Poll DD/MM/YYYY : TIME",
    questionPlaceholder: "พิมพ์คำถาม",
    choicePlaceholder: (index: number) => `ตัวเลือก ${index}`,
    defaultTitle: "ตัดสินใจด่วน",
    defaultQuestion: "เราควรเลือกอะไรดี?",
    defaultOptions: ["ใช่", "ไม่ใช่"],
    addChoice: "เพิ่มตัวเลือก",
    removeChoice: "ลบตัวเลือก",
    createButton: "สร้างโพล",
    creating: "กำลังสร้าง...",
    createError: "สร้างโพลไม่สำเร็จ",
    joinTitle: "เข้าร่วมโพล",
    joinButton: "เข้าร่วม",
    roomPlaceholder: "000000",
    roomCodeError: "กรอกรหัสห้อง 6 หลัก",
    chooseCreate: "สร้างโพล",
    chooseJoin: "เข้าร่วมโพล",
    backHome: "กลับ",
    createTitle: "สร้างโพลใหม่",
  },
  host: {
    missingToken: "ไม่มีโทเคนสำหรับแอดมิน",
    pollStopped: "หยุดโพลแล้ว",
    roomClosed: "ห้องถูกปิดแล้ว",
    realtimeFailed: "เชื่อมต่อเรียลไทม์ไม่สำเร็จ",
    connectingTitle: "กำลังเชื่อมต่อ...",
    warmingUp: "กำลังเตรียมห้องโหวต",
    stopPoll: "หยุดโพล",
    backHome: "กลับหน้าแรก",
    askAgain: "ถามคำถามใหม่",
    startPoll: "เริ่มโพลใหม่",
    startingPoll: "กำลังเริ่ม...",
    copyJoinLink: "คัดลอกลิงก์เข้าร่วม",
    linkCopied: "คัดลอกลิงก์แล้ว",
    linkCopyFailed: "คัดลอกลิงก์ไม่สำเร็จ",
    winnerLabel: "ชนะ",
    roomLabel: "ห้อง",
    qrAltPrefix: "คิวอาร์โค้ดสำหรับห้อง",
    votersLabel: "ผู้โหวต",
    graceTimerActive: "รอแอดมินกลับมา 30 วินาที",
    dashboardConnected: "แดชบอร์ดเชื่อมต่ออยู่",
    status: {
      live: "สด",
      reconnecting: "กำลังเชื่อมต่อใหม่",
      closed: "ปิดแล้ว",
      connecting: "กำลังเชื่อมต่อ",
    },
  },
  voter: {
    fallbackTitle: "Quick Poll",
    loadingQuestion: "กำลังโหลด...",
    pollEnded: "โพลสิ้นสุดแล้ว",
    roomUnavailable: "ห้องนี้ไม่พร้อมใช้งาน",
    clearVote: "ล้างคำตอบ",
    voteRecorded: "บันทึกคำตอบแล้ว",
    noVoteSelected: "ยังไม่ได้เลือกคำตอบ",
    resultsTitle: "ผลโหวต",
    winnerLabel: "ชนะ",
    backHome: "กลับหน้าแรก",
    status: {
      live: "สด",
      closed: "ปิดแล้ว",
      loading: "กำลังโหลด",
    },
  },
  api: {
    requestFailed: "คำขอไม่สำเร็จ",
  },
} as const;
